In [2]:
import numpy as np
import pandas as pd

In [3]:
import glob

In [5]:
df = pd.read_csv("TheLogGame.csv", index_col = False)

In [6]:
df = df.drop("Unnamed")

,Unnamed: 0,gameName,gameRank,gameRankUpDown,gameShares,gameTypeShares,sharesUpDown,timeCountTotal,avgUsedTime,userCountTotal,useStoreCount,publisher,payType,gameTypeName,date
0,0,"""리그 오브 레전드""",1,0,43.96,93.28,-0.94,1064167,104,613929,7991,"""라이엇게임즈""","""P""","""RTS""",2020-12-31
1,1,"""피파온라인4""",2,1,8.54,94.85,0.94,206673,59,208673,7810,"""넥슨""","""P""","""스포츠""",2020-12-31
2,2,"""서든어택""",3,-1,7.70,36.54,-0.33,186320,73,152465,7487,"""넥슨""","""P""","""FPS""",2020-12-31
3,3,"""배틀그라운드""",4,0,7.05,33.43,-0.37,170466,95,106982,7256,"""카카오/스팀""","""P""","""FPS""",2020-12-31
4,4,"""오버워치""",5,0,4.62,21.94,-0.12,111836,88,75568,7230,"""블리자드""","""P""","""FPS""",2020-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108914,108914,"""히어로즈 인 더 스카이""",291,2,0.01,0.04,0.00,1,0,0,0,"""게임어스""","""F""","""슈팅""",2019-12-28
108915,108915,"""시아""",292,0,0.01,0.01,0.01,1,14,5,0,"""(주)태울코리아""","""P""","""RPG""",2019-12-28
108916,108916,"""Elite Dangerous""",293,-5,0.01,0.01,0.00,1,0,0,0,"""스팀""","""P""","""RPG""",2019-12-28
108917,108917,"""로도스도 전기""",294,-19,0.01,0.01,0.00,0,0,0,0,"""(주)엘엔케이로직코리아""","""P""","""RPG""",2019-12-28
108918,108918,"""엠게임 테마맞고""",295,-3,0.01,0.01,0.00,0,0,0,0,"""엠게임""","""F""","""보드""",2019-12-28

In [7]:
df = df.drop('Unnamed: 0', axis = 1)

In [8]:
pf = df

In [9]:
lst = ['gameName', 'publisher', 'payType', 'gameTypeName']

In [8]:
#"" 지우기
for i in lst:
    a = i
    
    for j in range(len(pf[a])):
        pf[a][j] = pf[a][j].replace('"', '')

<ipython-input-8-e6a7ac28bb3d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pf[a][j] = pf[a][j].replace('"', '')

In [9]:
pf

,gameName,gameRank,gameRankUpDown,gameShares,gameTypeShares,sharesUpDown,timeCountTotal,avgUsedTime,userCountTotal,useStoreCount,publisher,payType,gameTypeName,date
0,리그 오브 레전드,1,0,43.96,93.28,-0.94,1064167,104,613929,7991,라이엇게임즈,P,RTS,2020-12-31
1,피파온라인4,2,1,8.54,94.85,0.94,206673,59,208673,7810,넥슨,P,스포츠,2020-12-31
2,서든어택,3,-1,7.70,36.54,-0.33,186320,73,152465,7487,넥슨,P,FPS,2020-12-31
3,배틀그라운드,4,0,7.05,33.43,-0.37,170466,95,106982,7256,카카오/스팀,P,FPS,2020-12-31
4,오버워치,5,0,4.62,21.94,-0.12,111836,88,75568,7230,블리자드,P,FPS,2020-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108914,히어로즈 인 더 스카이,291,2,0.01,0.04,0.00,1,0,0,0,게임어스,F,슈팅,2019-12-28
108915,시아,292,0,0.01,0.01,0.01,1,14,5,0,(주)태울코리아,P,RPG,2019-12-28
108916,Elite Dangerous,293,-5,0.01,0.01,0.00,1,0,0,0,스팀,P,RPG,2019-12-28
108917,로도스도 전기,294,-19,0.01,0.01,0.00,0,0,0,0,(주)엘엔케이로직코리아,P,RPG,2019-12-28
108918,엠게임 테마맞고,295,-3,0.01,0.01,0.00,0,0,0,0,엠게임,F,보드,2019-12-28

In [10]:
pf.to_csv("TheLogTextCleaned_0817.csv")

In [4]:
pf = pd.read_csv("TheLogTextCleaned_0817.csv")

In [5]:
pf[pf.gameName == "워록"]

,Unnamed: 0,gameName,gameRank,gameRankUpDown,gameShares,gameTypeShares,sharesUpDown,timeCountTotal,avgUsedTime,userCountTotal,useStoreCount,publisher,payType,gameTypeName,date
134,134,워록,135,-21,0.01,0.05,-0.01,232,67,205,89,넥슨,P,FPS,2020-12-31
413,413,워록,114,8,0.02,0.07,0.00,294,94,186,68,넥슨,P,FPS,2020-12-30
723,723,워록,122,0,0.02,0.06,0.00,232,77,179,83,넥슨,P,FPS,2020-12-29
1024,1024,워록,122,-8,0.02,0.06,0.00,261,91,172,67,넥슨,P,FPS,2020-12-28
1318,1318,워록,114,6,0.02,0.07,0.00,387,96,242,124,넥슨,P,FPS,2020-12-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107554,107554,워록,107,5,0.02,0.07,0.00,826,88,563,298,넥슨,P,FPS,2020-01-01
107855,107855,워록,112,-1,0.02,0.06,0.00,652,74,523,306,넥슨,P,FPS,2019-12-31
108146,108146,워록,111,-10,0.02,0.07,0.00,687,87,469,253,넥슨,P,FPS,2019-12-30
108430,108430,워록,101,10,0.02,0.07,0.00,963,100,574,299,넥슨,P,FPS,2019-12-29
108734,108734,워록,111,-2,0.02,0.06,0.00,809,87,554,297,넥슨,P,FPS,2019-12-28

In [6]:
#게임 이름 excel 파일형식으로
lst = list(pf['gameName'])
for i in range(len(lst)):
    lst[i] = ''.join(char for char in lst[i] if char.isalnum())
pf['gameName'] = lst

In [7]:
#날짜 바꾸기 20201231 형식으로
lst = list(pf['date'])
for i in range(len(lst)):
    lst[i] = ''.join(char for char in lst[i] if char.isalnum())
    lst[i] = int(lst[i])
pf['date'] = lst

In [8]:
path = "C:/Users/Hannah Kim/Desktop/프로시딩준비/LucyRaw2/*.xlsx"

긍정 dataframe = p

In [9]:
p = pd.DataFrame()
for fname in glob.glob(path):

    name = fname.split('_g_')[1]
    name = ''.join(char for char in name if char.isalnum())
    name = name.replace("xlsx", "")
    
    df = pd.read_excel(fname, sheet_name = '긍정')
    df['gameName'] = name
    df = df.rename(columns = {'구분':'date'})
    
    
    p = p.append(df)

In [17]:
p

,date,블로그,카페,커뮤니티,언론,페이스북,정부_공공,인스타그램,카카오스토리,기업_단체,지식인,트위터,유투브,gameName
0,20200101,7,6,4,0,0,0,0,0,0,0,0,1,피파온라인4
1,20200102,10,2,2,21,0,0,0,0,0,3,0,3,피파온라인4
2,20200103,7,3,9,111,0,0,0,0,0,2,0,0,피파온라인4
3,20200104,11,10,1,8,0,0,1,0,0,0,0,0,피파온라인4
4,20200105,9,5,0,2,0,0,0,0,0,4,0,1,피파온라인4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,20201227,0,0,1,1,0,0,0,0,0,0,0,0,로스트사가
362,20201228,0,0,0,0,0,0,0,0,0,0,0,0,로스트사가
363,20201229,1,0,0,0,0,0,0,0,0,0,0,0,로스트사가
364,20201230,0,2,0,0,0,0,0,0,0,0,0,0,로스트사가
365,20201231,0,0,1,0,0,0,0,0,0,0,0,0,로스트사가

In [19]:
avdf = pd.read_csv("avdf.csv")
avdf

,Unnamed: 0,gameName,gameshare,gameTypeshare,gameType,Positive,Negative,Neutral,Total,P/Total,P/N,N/P,N/Total
0,0,리그오브레전드,48.64,93.58,RTS,3392827,1370618,8297435,13060880,0.259770,2.475399,0.403975,0.104941
1,1,피파온라인4,6.77,91.57,스포츠,42237068,22345398,90010163,154592629,0.273215,1.890191,0.529047,0.144544
2,2,서든어택,5.57,26.34,FPS,788327,223825,809784,1821936,0.432686,3.522069,0.283924,0.122850
3,3,배틀그라운드,7.42,35.12,FPS,6458332,1596519,8098386,16153237,0.399817,4.045258,0.247203,0.098836
4,4,오버워치,6.03,28.53,FPS,1291454,528253,2435204,4254911,0.303521,2.444764,0.409037,0.124151
...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,156,넷마블캐릭챗,0.01,0.12,보드,3033118,1687043,6728592,11448753,0.264930,1.797890,0.556208,0.147356
157,157,트리오브세이비어,0.03,0.22,RPG,9002983,3283373,14745477,27031833,0.333051,2.741992,0.364698,0.121463
158,158,포키포키,0.01,0.07,액션,70533,24535,149232,244300,0.288715,2.874791,0.347851,0.100430
159,159,Factorio,0.01,0.01,RTS,67,481,236,784,0.085459,0.139293,7.179104,0.613520
160,160,포트리스2RED,0.01,12.60,슈팅,57578960,32430181,126840158,216849299,0.265525,1.775475,0.563230,0.149552

In [22]:
onesixty = list(avdf['gameName'])
plst = list(p['gameName'])
zerolst = []
for x in onesixty:
    if x not in plst:
        zerolst.append(x)
zerolst

['한게임라스베가스포커',
 '한게임파티훌라',
 '리니지리마스터테스트',
 '넷마블바둑nTV',
 '넷마블당구포켓볼',
 '엠게임컬투맞고',
 '엠게임하이로우',
 '피망틀린그림찾기',
 '넷마블베가세',
 '넷마블파워알까기',
 '피망상하이플러스',
 '엠게임훌라',
 '엠게임사천성',
 '넷마블캐릭챗']

In [27]:
l = ['블로그', '카페', '커뮤니티', '언론', '페이스북', '정부_공공', '인스타그램', '카카오스토리',
       '기업_단체', '지식인', '트위터', '유투브']
for i in range(len(zerolst)):
    zero = pd.DataFrame()
    zero['date'] = p[p.gameName == '워록']['date']
    for col in l:
        zero[col] = 0
    zero['gameName'] = zerolst[i]
    p = p.append(zero)

         date  블로그  카페  커뮤니티  언론  페이스북  정부_공공  인스타그램  카카오스토리  기업_단체  지식인  트위터  \
0    20200101    0   0     0   0     0      0      0       0      0    0    0
1    20200102    0   0     0   0     0      0      0       0      0    0    0
2    20200103    0   0     0   0     0      0      0       0      0    0    0
3    20200104    0   0     0   0     0      0      0       0      0    0    0
4    20200105    0   0     0   0     0      0      0       0      0    0    0
..        ...  ...  ..   ...  ..   ...    ...    ...     ...    ...  ...  ...
361  20201227    0   0     0   0     0      0      0       0      0    0    0
362  20201228    0   0     0   0     0      0      0       0      0    0    0
363  20201229    0   0     0   0     0      0      0       0      0    0    0
364  20201230    0   0     0   0     0      0      0       0      0    0    0
365  20201231    0   0     0   0     0      0      0       0      0    0    0

     유투브    gameName
0      0  한게임라스베가스포커
1      0  한게임라스베가스포커
2      0  한게임라스베가스포커
3      0  한게임라스베가스포커
4      0  한게임라스베가스포커
..   ...         ...
361    0  한게임라스베가스포커
362    0  한게임라스베가스포커
363    0  한게임라스베가스포커
364    0  한게임라스베가스포커
365    0  한게임라스베가스포커

[366 rows x 14 columns]
         date  블로그  카페  커뮤니티  언론  페이스북  정부_공공  인스타그램  카카오스토리  기업_단체  지식인  트위터  \
0    20200101    0   0     0   0     0      0      0       0      0    0    0
1    20200102    0   0     0   0     0      0      0       0      0    0    0
2    20200103    0   0     0   0     0      0      0       0      0    0    0
3    20200104    0   0     0   0     0      0      0       0      0    0    0
4    20200105    0   0     0   0     0      0      0       0      0    0    0
..        ...  ...  ..   ...  ..   ...    ...    ...     ...    ...  ...  ...
361  20201227    0   0     0   0     0      0      0       0      0    0    0
362  20201228    0   0     0   0     0      0      0       0      0    0    0
363  20201229    0   0     0   0     0      0      0       0      0    0    0
364  20201230    0   0     0   0     0      0      0       0      0    0    0
365  20201231    0   0     0   0     0      0      0       0      0    0    0

     유투브 gameName
0      0  한게임파티훌라
1      0  한게임파티훌라
2      0  한게임파티훌라
3      0  한게임파티훌라
4      0  한게임파티훌라
..   ...      ...
361    0  한게임파티훌라
362    0  한게임파티훌라
363    0  한게임파티훌라
364    0  한게임파티훌라
365    0  한게임파티훌라

[366 rows x 14 columns]
         date  블로그  카페  커뮤니티  언론  페이스북  정부_공공  인스타그램  카카오스토리  기업_단체  지식인  트위터  \
0    20200101    0   0     0   0     0      0      0       0      0    0    0
1    20200102    0   0     0   0     0      0      0       0      0    0    0
2    20200103    0   0     0   0     0      0      0       0      0    0    0
3    20200104    0   0     0   0     0      0      0       0      0    0    0
4    20200105    0   0     0   0     0      0      0       0      0    0    0
..        ...  ...  ..   ...  ..   ...    ...    ...     ...    ...  ...  ...
361  20201227    0   0     0   0     0      0      0       0      0    0    0
362  20201228    0   0     0   0     0      0      0       0      0    0    0
363  20201229    0   0     0   0     0      0      0       0      0    0    0
364  20201230    0   0     0   0     0      0      0       0      0    0    0
365  20201231    0   0     0   0     0      0      0       0      0    0    0

     유투브    gameName
0      0  리니지리마스터테스트
1      0  리니지리마스터테스트
2      0  리니지리마스터테스트
3      0  리니지리마스터테스트
4      0  리니지리마스터테스트
..   ...         ...
361    0  리니지리마스터테스트
362    0  리니지리마스터테스트
363    0  리니지리마스터테스트
364    0  리니지리마스터테스트
365    0  리니지리마스터테스트

[366 rows x 14 columns]
         date  블로그  카페  커뮤니티  언론  페이스북  정부_공공  인스타그램  카카오스토리  기업_단체  지식인  트위터  \
0    20200101    0   0     0   0     0      0      0       0      0    0    0
1    20200102    0   0     0   0     0      0      0       0      0    0    0
2    20200103    0   0     0   0     0      0      0       0      0    0    0
3    20200104    0   0     0   0     0      0      0       0      0    0    0
4    20200105    0   0     0   0     0      0      0       0      0    0    0
..        ...  ...  ..   ...  ..   ...    ...    ...     ...    ...  ...  ...
361  20201227    0   0     0   0     0      0      0       0      0    0    0
362  20201228    0   0     0   0     0      0      0       0      0    0    0
363  20201229    0   0     0   0     0      0      0       0      0    0    0
364  20201230    0   0     0   0     0      0      0       0      0    0    0
365  20201231    0   0     0   0     0      0      0       0      0    0    0

     유투브  gameName
0      0  넷마블바둑nTV
1      0  넷마블바둑nTV
2      0  넷마블바둑nTV
3      0  넷마블바둑nTV
4      0  넷마블바둑nTV
..   ...       ...
361    0  넷마블바둑nTV
362    0  넷마블바둑nTV
363    0  넷마블바둑nTV
364    0  넷마블바둑nTV
365    0  넷마블바둑nTV

[366 rows x 14 columns]
         date  블로그  카페  커뮤니티  언론  페이스북  정부_공공  인스타그램  카카오스토리  기업_단체  지식인  트위터  \
0    20200101    0   0     0   0     0      0      0       0      0    0    0
1    20200102    0   0     0   0     0      0      0       0      0    0    0
2    20200103    0   0     0   0     0      0      0       0      0    0    0
3    20200104    0   0     0   0     0      0      0       0      0    0    0
4    20200105    0   0     0   0     0      0      0       0      0    0    0
..        ...  ...  ..   ...  ..   ...    ...    ...     ...    ...  ...  ...
361  20201227    0   0     0   0     0      0      0       0      0    0    0
362  20201228    0   0     0   0     0      0      0       0      0    0    0
363  20201229    0   0     0   0     0      0      0       0      0    0    0
364  20201230    0   0     0   0     0      0      0       0      0    0    0
365  20201231    0   0     0   0     0      0      0       0      0    0    0

     유투브  gameName
0      0  넷마블당구포켓볼
1      0  넷마블당구포켓볼
2      0  넷마블당구포켓볼
3      0  넷마블당구포켓볼
4      0  넷마블당구포켓볼
..   ...       ...
361    0  넷마블당구포켓볼
362    0  넷마블당구포켓볼
363    0  넷마블당구포켓볼
364    0  넷마블당구포켓볼
365    0  넷마블당구포켓볼

[366 rows x 14 columns]
         date  블로그  카페  커뮤니티  언론  페이스북  정부_공공  인스타그램  카카오스토리  기업_단체  지식인  트위터  \
0    20200101    0   0     0   0     0      0      0       0      0    0    0
1    20200102    0   0     0   0     0      0      0       0      0    0    0
2    20200103    0   0     0   0     0      0      0       0      0    0    0
3    20200104    0   0     0   0     0      0      0       0      0    0    0
4    20200105    0   0     0   0     0      0      0       0      0    0    0
..        ...  ...  ..   ...  ..   ...    ...    ...     ...    ...  ...  ...
361  20201227    0   0     0   0     0      0      0       0      0    0    0
362  20201228    0   0     0   0     0      0      0       0      0    0    0
363  20201229    0   0     0   0     0      0      0       0      0    0    0
364  20201230    0   0     0   0     0      0      0       0      0    0    0
365  20201231    0   0     0   0     0      0      0       0      0    0    0

     유투브 gameName
0      0  엠게임컬투맞고
1      0  엠게임컬투맞고
2      0  엠게임컬투맞고
3      0  엠게임컬투맞고
4      0  엠게임컬투맞고
..   ...      ...
361    0  엠게임컬투맞고
362    0  엠게임컬투맞고
363    0  엠게임컬투맞고
364    0  엠게임컬투맞고
365    0  엠게임컬투맞고

[366 rows x 14 columns]
         date  블로그  카페  커뮤니티  언론  페이스북  정부_공공  인스타그램  카카오스토리  기업_단체  지식인  트위터  \
0    20200101    0   0     0   0     0      0      0       0      0    0    0
1    20200102    0   0     0   0     0      0      0       0      0    0    0
2    20200103    0   0     0   0     0      0      0       0      0    0    0
3    20200104    0   0     0   0     0      0      0       0      0    0    0
4    20200105    0   0     0   0     0      0      0       0      0    0    0
..        ...  ...  ..   ...  ..   ...    ...    ...     ...    ...  ...  ...
361  20201227    0   0     0   0     0      0      0       0      0    0    0
362  20201228    0   0     0   0     0      0      0       0      0    0    0
363  20201229    0   0     0   0     0      0      0       0      0    0    0
364  20201230    0   0     0   0     0      0      0       0      0    0    0
365  20201231    0   0     0   0     0      0      0       0      0    0    0

     유투브 gameName
0      0  엠게임하이로우
1      0  엠게임하이로우
2      0  엠게임하이로우
3      0  엠게임하이로우
4      0  엠게임하이로우
..   ...      ...
361    0  엠게임하이로우
362    0  엠게임하이로우
363    0  엠게임하이로우
364    0  엠게임하이로우
365    0  엠게임하이로우

[366 rows x 14 columns]
         date  블로그  카페  커뮤니티  언론  페이스북  정부_공공  인스타그램  카카오스토리  기업_단체  지식인  트위터  \
0    20200101    0   0     0   0     0      0      0       0      0    0    0
1    20200102    0   0     0   0     0      0      0       0      0    0    0
2    20200103    0   0     0   0     0      0      0       0      0    0    0
3    20200104    0   0     0   0     0      0      0       0      0    0    0
4    20200105    0   0     0   0     0      0      0       0      0    0    0
..        ...  ...  ..   ...  ..   ...    ...    ...     ...    ...  ...  ...
361  20201227    0   0     0   0     0      0      0       0      0    0    0
362  20201228    0   0     0   0     0      0      0       0      0    0    0
363  20201229    0   0     0   0     0      0      0       0      0    0    0
364  20201230    0   0     0   0     0      0      0       0      0    0    0
365  20201231    0   0     0   0     0      0      0       0      0    0    0

     유투브  gameName
0      0  피망틀린그림찾기
1      0  피망틀린그림찾기
2      0  피망틀린그림찾기
3      0  피망틀린그림찾기
4      0  피망틀린그림찾기
..   ...       ...
361    0  피망틀린그림찾기
362    0  피망틀린그림찾기
363    0  피망틀린그림찾기
364    0  피망틀린그림찾기
365    0  피망틀린그림찾기

[366 rows x 14 columns]
         date  블로그  카페  커뮤니티  언론  페이스북  정부_공공  인스타그램  카카오스토리  기업_단체  지식인  트위터  \
0    20200101    0   0     0   0     0      0      0       0      0    0    0
1    20200102    0   0     0   0     0      0      0       0      0    0    0
2    20200103    0   0     0   0     0      0      0       0      0    0    0
3    20200104    0   0     0   0     0      0      0       0      0    0    0
4    20200105    0   0     0   0     0      0      0       0      0    0    0
..        ...  ...  ..   ...  ..   ...    ...    ...     ...    ...  ...  ...
361  20201227    0   0     0   0     0      0      0       0      0    0    0
362  20201228    0   0     0   0     0      0      0       0      0    0    0
363  20201229    0   0     0   0     0      0      0       0      0    0    0
364  20201230    0   0     0   0     0      0      0       0      0    0    0
365  20201231    0   0     0   0     0      0      0       0      0    0    0

     유투브 gameName
0      0   넷마블베가세
1      0   넷마블베가세
2      0   넷마블베가세
3      0   넷마블베가세
4      0   넷마블베가세
..   ...      ...
361    0   넷마블베가세
362    0   넷마블베가세
363    0   넷마블베가세
364    0   넷마블베가세
365    0   넷마블베가세

[366 rows x 14 columns]
         date  블로그  카페  커뮤니티  언론  페이스북  정부_공공  인스타그램  카카오스토리  기업_단체  지식인  트위터  \
0    20200101    0   0     0   0     0      0      0       0      0    0    0
1    20200102    0   0     0   0     0      0      0       0      0    0    0
2    20200103    0   0     0   0     0      0      0       0      0    0    0
3    20200104    0   0     0   0     0      0      0       0      0    0    0
4    20200105    0   0     0   0     0      0      0       0      0    0    0
..        ...  ...  ..   ...  ..   ...    ...    ...     ...    ...  ...  ...
361  20201227    0   0     0   0     0      0      0       0      0    0    0
362  20201228    0   0     0   0     0      0      0       0      0    0    0
363  20201229    0   0     0   0     0      0      0       0      0    0    0
364  20201230    0   0     0   0     0      0      0       0      0    0    0
365  20201231    0   0     0   0     0      0      0       0      0    0    0

     유투브  gameName
0      0  넷마블파워알까기
1      0  넷마블파워알까기
2      0  넷마블파워알까기
3      0  넷마블파워알까기
4      0  넷마블파워알까기
..   ...       ...
361    0  넷마블파워알까기
362    0  넷마블파워알까기
363    0  넷마블파워알까기
364    0  넷마블파워알까기
365    0  넷마블파워알까기

[366 rows x 14 columns]

         date  블로그  카페  커뮤니티  언론  페이스북  정부_공공  인스타그램  카카오스토리  기업_단체  지식인  트위터  \
0    20200101    0   0     0   0     0      0      0       0      0    0    0
1    20200102    0   0     0   0     0      0      0       0      0    0    0
2    20200103    0   0     0   0     0      0      0       0      0    0    0
3    20200104    0   0     0   0     0      0      0       0      0    0    0
4    20200105    0   0     0   0     0      0      0       0      0    0    0
..        ...  ...  ..   ...  ..   ...    ...    ...     ...    ...  ...  ...
361  20201227    0   0     0   0     0      0      0       0      0    0    0
362  20201228    0   0     0   0     0      0      0       0      0    0    0
363  20201229    0   0     0   0     0      0      0       0      0    0    0
364  20201230    0   0     0   0     0      0      0       0      0    0    0
365  20201231    0   0     0   0     0      0      0       0      0    0    0

     유투브  gameName
0      0  피망상하이플러스
1      0  피망상하이플러스
2      0  피망상하이플러스
3      0  피망상하이플러스
4      0  피망상하이플러스
..   ...       ...
361    0  피망상하이플러스
362    0  피망상하이플러스
363    0  피망상하이플러스
364    0  피망상하이플러스
365    0  피망상하이플러스

[366 rows x 14 columns]
         date  블로그  카페  커뮤니티  언론  페이스북  정부_공공  인스타그램  카카오스토리  기업_단체  지식인  트위터  \
0    20200101    0   0     0   0     0      0      0       0      0    0    0
1    20200102    0   0     0   0     0      0      0       0      0    0    0
2    20200103    0   0     0   0     0      0      0       0      0    0    0
3    20200104    0   0     0   0     0      0      0       0      0    0    0
4    20200105    0   0     0   0     0      0      0       0      0    0    0
..        ...  ...  ..   ...  ..   ...    ...    ...     ...    ...  ...  ...
361  20201227    0   0     0   0     0      0      0       0      0    0    0
362  20201228    0   0     0   0     0      0      0       0      0    0    0
363  20201229    0   0     0   0     0      0      0       0      0    0    0
364  20201230    0   0     0   0     0      0      0       0      0    0    0
365  20201231    0   0     0   0     0      0      0       0      0    0    0

     유투브 gameName
0      0    엠게임훌라
1      0    엠게임훌라
2      0    엠게임훌라
3      0    엠게임훌라
4      0    엠게임훌라
..   ...      ...
361    0    엠게임훌라
362    0    엠게임훌라
363    0    엠게임훌라
364    0    엠게임훌라
365    0    엠게임훌라

[366 rows x 14 columns]
         date  블로그  카페  커뮤니티  언론  페이스북  정부_공공  인스타그램  카카오스토리  기업_단체  지식인  트위터  \
0    20200101    0   0     0   0     0      0      0       0      0    0    0
1    20200102    0   0     0   0     0      0      0       0      0    0    0
2    20200103    0   0     0   0     0      0      0       0      0    0    0
3    20200104    0   0     0   0     0      0      0       0      0    0    0
4    20200105    0   0     0   0     0      0      0       0      0    0    0
..        ...  ...  ..   ...  ..   ...    ...    ...     ...    ...  ...  ...
361  20201227    0   0     0   0     0      0      0       0      0    0    0
362  20201228    0   0     0   0     0      0      0       0      0    0    0
363  20201229    0   0     0   0     0      0      0       0      0    0    0
364  20201230    0   0     0   0     0      0      0       0      0    0    0
365  20201231    0   0     0   0     0      0      0       0      0    0    0

     유투브 gameName
0      0   엠게임사천성
1      0   엠게임사천성
2      0   엠게임사천성
3      0   엠게임사천성
4      0   엠게임사천성
..   ...      ...
361    0   엠게임사천성
362    0   엠게임사천성
363    0   엠게임사천성
364    0   엠게임사천성
365    0   엠게임사천성

[366 rows x 14 columns]
         date  블로그  카페  커뮤니티  언론  페이스북  정부_공공  인스타그램  카카오스토리  기업_단체  지식인  트위터  \
0    20200101    0   0     0   0     0      0      0       0      0    0    0
1    20200102    0   0     0   0     0      0      0       0      0    0    0
2    20200103    0   0     0   0     0      0      0       0      0    0    0
3    20200104    0   0     0   0     0      0      0       0      0    0    0
4    20200105    0   0     0   0     0      0      0       0      0    0    0
..        ...  ...  ..   ...  ..   ...    ...    ...     ...    ...  ...  ...
361  20201227    0   0     0   0     0      0      0       0      0    0    0
362  20201228    0   0     0   0     0      0      0       0      0    0    0
363  20201229    0   0     0   0     0      0      0       0      0    0    0
364  20201230    0   0     0   0     0      0      0       0      0    0    0
365  20201231    0   0     0   0     0      0      0       0      0    0    0

     유투브 gameName
0      0   넷마블캐릭챗
1      0   넷마블캐릭챗
2      0   넷마블캐릭챗
3      0   넷마블캐릭챗
4      0   넷마블캐릭챗
..   ...      ...
361    0   넷마블캐릭챗
362    0   넷마블캐릭챗
363    0   넷마블캐릭챗
364    0   넷마블캐릭챗
365    0   넷마블캐릭챗

[366 rows x 14 columns]

부정 dataframe = n

In [29]:
n = pd.DataFrame()
for fname in glob.glob(path):

    name = fname.split('_g_')[1]
    name = ''.join(char for char in name if char.isalnum())
    name = name.replace("xlsx", "")
    
    df = pd.read_excel(fname, sheet_name = '부정')
    df['gameName'] = name
    df = df.rename(columns = {'구분':'date'})
    
    
    n = n.append(df)

In [30]:
l = ['블로그', '카페', '커뮤니티', '언론', '페이스북', '정부_공공', '인스타그램', '카카오스토리',
       '기업_단체', '지식인', '트위터', '유투브']
for i in range(len(zerolst)):
    zero = pd.DataFrame()
    zero['date'] = p[p.gameName == '워록']['date']
    for col in l:
        zero[col] = 0
    zero['gameName'] = zerolst[i]
    n = n.append(zero)

중립 데이터 프레임 = neu

In [31]:
neu = pd.DataFrame()
for fname in glob.glob(path):

    name = fname.split('_g_')[1]
    name = ''.join(char for char in name if char.isalnum())
    name = name.replace("xlsx", "")
    
    df = pd.read_excel(fname, sheet_name = '중립')
    df['gameName'] = name
    df = df.rename(columns = {'구분':'date'})
    
    
    neu = neu.append(df)

In [32]:
l = ['블로그', '카페', '커뮤니티', '언론', '페이스북', '정부_공공', '인스타그램', '카카오스토리',
       '기업_단체', '지식인', '트위터', '유투브']
for i in range(len(zerolst)):
    zero = pd.DataFrame()
    zero['date'] = p[p.gameName == '워록']['date']
    for col in l:
        zero[col] = 0
    zero['gameName'] = zerolst[i]
    neu = neu.append(zero)

In [33]:
pf = pd.merge(pf, p, on=['date', 'gameName'])

In [34]:
pf = pd.merge(pf, n, on=['date', 'gameName'])

In [35]:
pf = pd.merge(pf, neu, on=['date', 'gameName'])

In [37]:
pf = pf.drop("Unnamed: 0", axis = 1)

In [38]:
pf.to_csv("merged_lucy_0818.csv")

In [39]:
pf

,gameName,gameRank,gameRankUpDown,gameShares,gameTypeShares,sharesUpDown,timeCountTotal,avgUsedTime,userCountTotal,useStoreCount,...,커뮤니티,언론,페이스북,정부_공공,인스타그램,카카오스토리,기업_단체,지식인,트위터,유투브
0,리그오브레전드,1,0,43.96,93.28,-0.94,1064167,104,613929,7991,...,670,126,5,2,49,0,117,373,612,85
1,피파온라인4,2,1,8.54,94.85,0.94,206673,59,208673,7810,...,15,4,0,0,3,0,0,43,1,42
2,서든어택,3,-1,7.70,36.54,-0.33,186320,73,152465,7487,...,14,9,10,0,0,0,2,15,41,79
3,배틀그라운드,4,0,7.05,33.43,-0.37,170466,95,106982,7256,...,11,83,3,0,7,0,0,60,77,104
4,오버워치,5,0,4.62,21.94,-0.12,111836,88,75568,7230,...,137,35,7,0,5,0,4,92,377,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58921,포키포키,226,3,0.01,0.05,0.00,79,79,60,21,...,0,0,0,0,0,0,0,0,15,0
58922,엠게임훌라,240,-23,0.01,0.07,0.00,55,77,43,19,...,0,0,0,0,0,0,0,0,0,0
58923,엠게임사천성,242,-3,0.01,0.07,0.00,53,53,60,29,...,0,0,0,0,0,0,0,0,0,0
58924,피망상하이플러스,249,7,0.01,0.06,0.00,47,52,54,24,...,0,0,0,0,0,0,0,0,0,0
58925,내맘대로Z9별,255,-55,0.01,0.01,0.00,38,41,56,20,...,0,0,0,0,0,0,0,0,0,0

#실패
path = "C:/Users/Hannah Kim/Desktop/프로시딩준비/LucyRaw/*.xlsx"
x = '리그오브레전드'
y = '20201231'
y = int(y)
for fname in glob.glob(path):
    name = fname.split('_g_')[1]
    name = ''.join(char for char in name if char.isalnum())
    if x in name:
        df = pd.read_excel(fname, sheet_name = '긍정')
        df.loc[df['구분'] == y]